### ISSUE TITLE
Jacobian matrix problem

### ISSUE THREAD

**Issue by UNKL3AR** [NoneJou072/robopal#1]
When I used this environment to write my control algorithm, I encountered the problem of qp solution failure. The temporary troubleshooting may be related to the Jacobian matrix. I called mujoco's official function `mj_jacBody` and found that it was different from the Jacobian matrix solved by `Pinocchio`.Here is some code I used for testing：
```
self.q_cur = self.robot.single_arm.arm_qpos
self.qd_curr = self.robot.single_arm.arm_qvel
jacpp = np.zeros((3, 7))
jacrr = np.zeros((3, 7))
i = mujoco.mj_name2id(self.mj_model,mujoco.mjtObj.mjOBJ_JOINT,'0_j7')
mujoco.mj_jacBody(self.mj_model, self.mj_data, jacpp, jacrr, i)
jac_mujoco = np.block([[jacpp],[jacrr]])
print("-------------------------------------------------")
print(jac_mujoco)
print("-------------------------------------------------")
print(self.mpcctrl.kdl_solver.get_full_jac(self.q_cur))
print("-------------------------------------------------")
```
And print out the data for comparison：

> [[-3.52641352e-02 -1.26666646e-01  2.75101541e-03 -2.00961146e-01
   0.00000000e+00  0.00000000e+00  0.00000000e+00]
 [-7.29223053e-01  4.25623553e-02  5.04373076e-01  9.66331027e-02
   0.00000000e+00  0.00000000e+00  0.00000000e+00]
 [-5.35717882e-06  7.02463703e-01  1.19878774e-01 -4.01949952e-01
   0.00000000e+00  0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00 -3.18573595e-01  5.72771181e-01  5.30837222e-03
   8.43820542e-01  0.00000000e+00  0.00000000e+00]
 [ 7.34642000e-06 -9.47898130e-01 -1.92504295e-01  9.72882845e-01
   1.19731535e-01  0.00000000e+00  0.00000000e+00]
 [-1.00000000e+00 -1.12063002e-05  7.96790606e-01  2.31237523e-01
  -5.23097746e-01  0.00000000e+00  0.00000000e+00]]
---
>[[ 6.32547097e-04  2.83820826e-01  5.75103337e-02 -6.30569353e-01
  -3.30706630e-02  8.23511408e-02  1.06270151e-01]
 [ 8.70580000e-05 -9.53874899e-02  1.71303821e-01 -6.97121067e-02
   7.46916985e-01 -3.55061901e-01  7.71831333e-01]
 [ 6.39563780e-10 -2.84735302e-04  4.56948495e-05  3.07773819e-01
   1.17613646e-01 -1.68126892e-01 -2.50614528e-01]
 [ 0.00000000e+00 -3.18572979e-01  5.72770727e-01  5.30769330e-03
   8.43820775e-01  5.35279248e-01  7.49185549e-01]
 [ 7.34641021e-06 -9.47898337e-01 -1.92503849e-01  9.72883049e-01
   1.19730998e-01 -2.56872621e-01 -2.95613575e-01]
 [-1.00000000e+00 -1.06368551e-05  7.96791041e-01  2.31236679e-01
  -5.23097493e-01  8.04669238e-01 -5.92734027e-01]]

**Comment by NoneJou072** [comment]
I have fixed this problem by using 'computeFrameJacobian' in pinocchio. Please pull the latest repo version.
