### ISSUE TITLE
  File "/home/cjs/anaconda3/envs/robopal/lib/python3.10/site-packages/numpy/core/shape_base.py", line 357, in hstack     return _nx.concatenate(arrs, 0, dtype=dtype, casting=casting) ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 1 dimension(s) and the array at index 2 has 2 dimension(s)

### ISSUE THREAD

**Issue by DevilCJS89** [NoneJou072/robopal#13]
非常感谢您的分享！
我在尝试学习和使用这个框架的时遇到一些问题，
请帮忙看一下我的环境配置是否有问题：
environments:
python3.10.14
Package                       Version     Editable project location
----------------------------- ----------- -------------------------
absl-py                       2.1.0
actionlib                     1.14.0
angles                        1.9.13
aruco_detect                  0.12.0
base_local_planner            1.17.3
bondpy                        1.8.6
camera-calibration            1.17.0
camera-calibration-parsers    1.12.0
catkin                        0.8.10
cloudpickle                   3.0.0
contourpy                     1.2.1
controller-manager            0.20.0
controller-manager-msgs       0.19.6
cv-bridge                     1.16.2
cycler                        0.12.1
diagnostic-analysis           1.11.0
diagnostic-common-diagnostics 1.11.0
diagnostic-updater            1.11.0
dynamic-reconfigure           1.7.3
etils                         1.7.0
evdev                         1.7.1
Farama-Notifications          0.0.4
fonttools                     4.51.0
fsspec                        2024.3.1
gazebo_plugins                2.9.2
gazebo_ros                    2.9.2
gencpp                        0.7.0
geneus                        3.0.0
genlisp                       0.4.18
genmsg                        0.6.0
gennodejs                     2.0.2
genpy                         0.6.15
glfw                          2.7.0
gymnasium                     0.29.1
image-geometry                1.16.2
importlib_resources           6.4.0
interactive-markers           1.12.0
joint-state-publisher         1.15.1
joint-state-publisher-gui     1.15.1
kiwisolver                    1.4.5
laser_geometry                1.6.7
matplotlib                    3.8.4
message-filters               1.16.0
moveit-commander              1.1.13
moveit-core                   1.1.13
moveit-python                 0.4.5
moveit-ros-planning-interface 1.1.13
moveit-ros-visualization      1.1.13
moveit-task-constructor-core  0.1.3
mujoco                        3.1.5
numpy                         1.26.4
opencv-contrib-python         4.9.0.80
opencv-python                 4.9.0.80
packaging                     24.0
pillow                        10.3.0
pip                           24.0
pynput                        1.7.7
PyOpenGL                      3.1.7
pyparsing                     3.1.2
python-dateutil               2.9.0.post0
python-qt-binding             0.4.4
python-xlib                   0.33
qt-dotgraph                   0.4.2
qt-gui                        0.4.2
qt-gui-cpp                    0.4.2
qt-gui-py-common              0.4.2
resource_retriever            1.12.7
robopal                       0.4.0       /home/cjs/MUJOCO/robopal
ros_numpy                     0.0.5
rosbag                        1.16.0
rosboost-cfg                  1.15.8
rosclean                      1.15.8
roscreate                     1.15.8
rosgraph                      1.16.0
roslaunch                     1.16.0
roslib                        1.15.8
roslint                       0.12.0
roslz4                        1.16.0
rosmake                       1.15.8
rosmaster                     1.16.0
rosmsg                        1.16.0
rosnode                       1.16.0
rosparam                      1.16.0
rospy                         1.16.0
rospy_message_converter       0.5.9
rosserial_python              0.9.2
rosservice                    1.16.0
rostest                       1.16.0
rostopic                      1.16.0
rosunit                       1.15.8
roswtf                        1.16.0
rqt_action                    0.4.9
rqt_bag                       0.5.1
rqt_bag_plugins               0.5.1
rqt-console                   0.4.12
rqt_dep                       0.4.12
rqt_graph                     0.4.14
rqt_gui                       0.5.3
rqt_gui_py                    0.5.3
rqt-image-view                0.4.17
rqt_launch                    0.4.9
rqt-logger-level              0.4.12
rqt-moveit                    0.5.11
rqt_msg                       0.4.10
rqt-multiplot                 0.0.12
rqt_nav_view                  0.5.7
rqt_plot                      0.4.13
rqt_pose_view                 0.5.11
rqt_publisher                 0.4.10
rqt_py_common                 0.5.3
rqt_py_console                0.4.10
rqt-reconfigure               0.5.5
rqt-robot-dashboard           0.5.8
rqt-robot-monitor             0.5.15
rqt_robot_steering            0.5.12
rqt-runtime-monitor           0.5.10
rqt-rviz                      0.7.0
rqt_service_caller            0.4.10
rqt_shell                     0.4.11
rqt_srv                       0.4.9
rqt-tf-tree                   0.6.4
rqt_top                       0.4.10
rqt_topic                     0.4.13
rqt_web                       0.4.10
ruckig                        0.9.2
rviz                          1.14.20
sensor-msgs                   1.13.1
setuptools                    69.5.1
six                           1.16.0
smach                         2.5.2
smach-ros                     2.5.2
smclib                        1.8.6
some-package                  0.1
srdfdom                       0.6.4
tf                            1.13.2
tf-conversions                1.13.2
tf2-geometry-msgs             0.7.7
tf2-kdl                       0.7.7
tf2-py                        0.7.7
tf2-ros                       0.7.7
tf2-sensor-msgs               0.7.7
topic-tools                   1.16.0
trac_ik_python                1.6.6
turtlebot3_example            1.2.5
turtlebot3_teleop             1.2.5
typing_extensions             4.11.0
urdfdom-py                    0.4.6
wheel                         0.43.0
xacro                         1.14.16
zipp                          3.18.1

**Comment by DevilCJS89** [comment]
多个demo出现这个error：
  File "/home/cjs/anaconda3/envs/robopal/lib/python3.10/site-packages/numpy/core/shape_base.py", line 357, in hstack
    return _nx.concatenate(arrs, 0, dtype=dtype, casting=casting)
ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 1 dimension(s) and the array at index 2 has 2 dimension(s)
/home/cjs/anaconda3/envs/robopal/lib/python3.10/site-packages/glfw/__init__.py:914: GLFWError: (65537) b'The GLFW library is not initialized'

**Comment by NoneJou072** [comment]
似乎是mujoco 版本的问题，尝试降低一个小版本到3.1.4

**Comment by DevilCJS89** [comment]
Got it
Thank you！
