### ISSUE TITLE
AttributeError: 'JointImpedanceController' object has no attribute 'ik'

### ISSUE THREAD

**Issue by DevilCJS89** [NoneJou072/robopal#16]
您好！我遇到一些关于“ik” 的问题，看起来像是版本的原因！
请帮忙看一下下面的问题：
我对docementation/Gymnasium Style Interface中的示例code进行了修改，run以后遇到下面的问题！
问题1：
File "/home/cjs/MUJOCO/robopal/robopal/demos/manipulation_tasks/robot_manipulate.py", line 131, in set_random_init_position
    qpos = self.controller.ik(random_pos, self.init_quat[agent], q_init=self.robot.get_arm_qpos(agent))
AttributeError: 'JointImpedanceController' object has no attribute 'ik'

这个是我在调用rrt算法的时候遇到的问题
问题2：  
File "/home/cjs/MUJOCO/robopal/robopal/controllers/planners/rrt.py", line 395, in is_collide
    qpos = sim.ik(target_pos, target_rot, sim.robot.get_arm_qpos())
AttributeError: 'RobotEnv' object has no attribute 'ik'

**Comment by DevilCJS89** [comment]
这两个问题好像是因为envs/robot.py中的class RobotEnv(MujocoEnv): 里面没有定义ik的样子
是版本更新了相关类的定义吗？

**Comment by DevilCJS89** [comment]
这是我修改后的docementation/Gymnasium Style Interface中的示例code
code:
------------------------------------
from stable_baselines3 import HerReplayBuffer
from sb3_contrib import TQC
from stable_baselines3.common.callbacks import BaseCallback
from robopal.demos.manipulation_tasks.demo_pick_place import PickAndPlaceEnv
from robopal.commons.gym_wrapper import GoalEnvWrapper


class TensorboardCallback(BaseCallback):
    """
    Custom callback for plotting additional values in tensorboard.
    """

    def __init__(self, log_dir, verbose=0):
        super(TensorboardCallback, self).__init__(verbose)
        self.log_dir = log_dir

    def _on_step(self) -> bool:
        if self.n_calls % 51200 == 0:
            self.model.save(self.log_dir + f"/model_saved/TQC/diana_pick_place_v2_{self.n_calls}")
        return True
log_dir = "log/"

env = PickAndPlaceEnv(
    render_mode="human",
    control_freq=10,
    controller='JNTIMP',
)
env = GoalEnvWrapper(env)

# Initialize the model
model = TQC(
    'MultiInputPolicy',
    env,
    replay_buffer_class=HerReplayBuffer,
    # Parameters for HER
    replay_buffer_kwargs=dict(
        n_sampled_goal=4,
        goal_selection_strategy="future",
    ),
    verbose=1,
    tensorboard_log=log_dir,
    batch_size=1024,
    gamma=0.95,
    tau=0.05,
    policy_kwargs=dict(n_critics=2, net_arch=[512, 512, 512]),
)

# Train the model
model.learn(int(1e6), callback=TensorboardCallback(log_dir=log_dir))

**Comment by NoneJou072** [comment]
示例的版本是比较落后的。在初始化环境时，应该设置 controller='CARTIK ，选择 IK 控制器。最近的版本中把 ik 方法放入到了控制器中，改成 qpos = sim.controller.ik(target_pos, target_rot, sim.robot.get_arm_qpos())。
不过，由于 motion planning 这个脚本年久失修，可能因为某种原因无法成功规划，期待好心人帮忙解决ing

**Comment by DevilCJS89** [comment]
示例和运动规划的都已经解决了，示例的code修改就是上面的第三个。
