### ISSUE TITLE
运行demo_force_visual.py文件遇到报错ModuleNotFoundError: No module named 'robopal.demos.demo_admit_rl'

### ISSUE THREAD

**Issue by HJX-exoskeleton** [NoneJou072/robopal#22]
运行/robopal/plugins/unity_interface/demo_force_visual.py文件遇到如下报错：
/home/hjx/anaconda3/envs/hjx/bin/python /home/hjx/hjx_file/mujoco_file/robopal/robopal/plugins/unity_interface/demo_force_visual.py 
Traceback (most recent call last):
  File "/home/hjx/hjx_file/mujoco_file/robopal/robopal/plugins/unity_interface/demo_force_visual.py", line 2, in <module>
    from robopal.demos.demo_admit_rl.demo_admit_test import AdmitGymEnv
ModuleNotFoundError: No module named 'robopal.demos.demo_admit_rl'

**Comment by NoneJou072** [comment]
抱歉，这个脚本暂时弃用了
