### ISSUE TITLE
关于阻抗控制

### ISSUE THREAD

**Issue by my52** [NoneJou072/robopal#23]
你好，我想问一下这个能实现以期望的接触力沿轨迹移动吗

**Comment by NoneJou072** [comment]
这个框架只提供了基础的阻抗控制器，如果要实现以期望的接触力沿轨迹移动，需要你手动调整参数，修改并优化算法

**Comment by my52** [comment]
好的谢谢，请问怎么获取末端的受力呢，控制器里面好像没有用到接触力的样子。我在网上没找到获取接触力的相关资料。

**Comment by NoneJou072** [comment]
@my52 , 可以在您的 xml 文件中添加六维传感器，具体可以查阅 mujoco 官方文档的 sensor 部分：https://mujoco.readthedocs.io/en/stable/XMLreference.html#sensor

**Comment by my52** [comment]
谢谢佬！我研究研究
