### ISSUE TITLE
之后能开发出人形机器人训练的API么？

### ISSUE THREAD

**Issue by formoree** [NoneJou072/robopal#26]
后续开发中可以让项目不仅仅局限于机械臂，还能用于人形机器人昂！

**Comment by NoneJou072** [comment]
@formoree  ，感谢您的建议。
答案是可以的。不过，目前我的技术栈只局限在机械臂上，所以接入人形机器人训练 API 会是一个漫长的计划。
如果您有兴趣，可以 fork 本项目，自行更改代码，以适配人型机器人。这一路线是可行的，因为已经有其他人试验过了。

**Comment by formoree** [comment]
欸欸好的好的
