### ISSUE TITLE
大佬有计划实现下远程控制吗，像robosuite里面的keyboard和spacemouse控制

### ISSUE THREAD

**Issue by kunpeng-wu** [NoneJou072/robopal#8]

**Comment by NoneJou072** [comment]
感谢您的建议。
我近期会实现 keyboard 控制双臂运动，spacemouse 在计划中。

**Comment by kavinwkp** [comment]
大佬，我原始的xml文件里面有`contact`标签，但是生成的`robot.xml`里面的contact的关节没有前缀`0_`

**Comment by NoneJou072** [comment]
> 大佬，我试着移植了一下robosuite的键盘控制，但是好像和mujoco的快捷键冲突了，可以加下qq交流一下吗1817136760

好的，我加你了

**Comment by NoneJou072** [comment]
> 大佬，我原始的xml文件里面有`contact`标签，但是生成的`robot.xml`里面的contact的关节没有前缀`0_`

是的，目前还没有设置添加 contact 标签时自动添加前缀，目前许多高级的标签都不能使用。
已收到您的反馈，近期会更新支持 contact 标签

**Comment by NoneJou072** [comment]
> > 大佬，我试着移植了一下robosuite的键盘控制，但是好像和mujoco的快捷键冲突了，可以加下qq交流一下吗1817136760
> 
> 好的，我加你了

如果您实现该功能了，欢迎提交 PR
