### ISSUE TITLE
环境问题

### ISSUE THREAD

**Issue by Ykizi** [NoneJou072/robopal#9]
关于强化学习控制机械臂目前只有Pick-and-Place任务吗？

**Comment by NoneJou072** [comment]
目前是的，可以参照这个环境搭建自己的环境

**Comment by NoneJou072** [comment]
> 目前是的，可以参照这个环境搭建自己的环境

还有拉抽屉和开柜子门的环境

**Comment by Ykizi** [comment]
不好意思我没有找到

**Comment by NoneJou072** [comment]
> 不好意思我没有找到

robopal.demos.manipulation_tasks/*
